discord:
  token: YOUR_DISCORD_BOT_TOKEN
  oauth_client_id: YOUR_DISCORD_OAUTH_CLIENT_ID
  oauth_client_secret: YOUR_DISCORD_OAUTH_CLIENT_SECRET
  server_id: YOUR_DISCORD_SERVER_ID
  server_invite_url: https://discord.gg/YOUR_INVITE_CODE
  admin_role_ids: [ROLE_ID_1, ROLE_ID_2]
  moderator_role_ids: [ROLE_ID_1, ROLE_ID_2]
  trusted_role_ids: [ROLE_ID_1, ROLE_ID_2]
