# Example credentials file
# Copy this structure to your actual credentials using:
# EDITOR="nano" rails credentials:edit
#
# All values shown here are examples and should be replaced with your actual values

discord:
  token: YOUR_DISCORD_BOT_TOKEN
  oauth_client_id: YOUR_DISCORD_OAUTH_CLIENT_ID
  oauth_client_secret: YOUR_DISCORD_OAUTH_CLIENT_SECRET
  server_id: YOUR_DISCORD_SERVER_ID
  server_invite_url: https://discord.gg/YOUR_INVITE_CODE
  admin_role_ids: [ROLE_ID_1, ROLE_ID_2]
  moderator_role_ids: [ROLE_ID_1, ROLE_ID_2]
  trusted_role_ids: [ROLE_ID_1, ROLE_ID_2]

# To set up your credentials:
# 1. Run: EDITOR="nano" rails credentials:edit
# 2. Copy the structure above and replace with your actual values
# 3. Save and close the editor
# 4. Run: rails db:seed to sync settings to database
